worker_heartbeat_timeout: 300000

num_workers: 1

logging:
    level: info

services:
  - module: lib/index.js
    entrypoint: apiServiceWorker
    conf:
        mwApis:
        - uri: 'http://localhost:8080/api.php'
          domain: 'localhost'
        serverPort: 8142
